# Generated by Django 4.1.7 on 2023-02-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('representante', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, default='', max_length=500)),
                ('num_estacion', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Comunidades',
                'ordering': ['fecha_modificacion'],
            },
        ),
    ]
