# Generated by Django 4.1.7 on 2023-02-27 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cajas', '0001_initial'),
        ('comunidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('en_atencion', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('caja', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='cajas.caja')),
                ('comunidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='comunidades.comunidad')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
                'ordering': ['-numero'],
            },
        ),
    ]
