# Generated by Django 4.1.7 on 2023-03-06 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['numero'], 'verbose_name_plural': 'Turnos'},
        ),
    ]
