# Generated by Django 4.1.7 on 2023-03-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
