# Generated by Django 4.1.7 on 2023-03-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_alter_link_options_link_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='fila_inicial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
